processes:
  proxy:
    description: The proxy Application
    command: go run ./proxy/main.go
    ready_log_line: "revProxyTLS server started"
  enclave:
    description: The Enclave Application
    command: go run ./enclave/main.go
    ready_log_line: "enclave serverTLS started"
    depends_on:
      proxy:
        condition: process_log_ready
  nonclave:
    description: The Non-Enclave Application
    command: go run ./nonclave/main.go
    depends_on:
      enclave:
        condition: process_log_ready
      proxy:
        condition: process_log_ready
    availability:
      exit_on_end: true
